import { mutation } from "./_generated/server";

/**
 * Seed function to add initial exams to the database
 * Run this once from Convex dashboard or via API
 */
export const seedExams = mutation({
  handler: async (ctx) => {
    const now = Date.now();
    const systemUserId = "system"; // Default creator for seeded exams

    const exams = [
      // General Licensure Examinations
      {
        name: "Saudi Medical Licensure Examination",
        slug: "smle",
        abbreviation: "SMLE",
        description: "SMLE - General Practitioner licensure examination",
        category: "Doctor (General Practitioner)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Dental Licensure Examination",
        slug: "sdle",
        abbreviation: "SDLE",
        description: "SDLE - General Dentist licensure examination",
        category: "Dentist (General)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Pharmacist Licensure Examination",
        slug: "sple",
        abbreviation: "SPLE",
        description: "SPLE - Pharmacist licensure examination",
        category: "Pharmacist",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Nursing Licensure Examination",
        slug: "snle",
        abbreviation: "SNLE",
        description: "SNLE - Nurse licensure examination",
        category: "Nurse",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Laboratory Licensure Examination",
        slug: "slle",
        abbreviation: "SLLE",
        description: "SLLE - Laboratory Specialist/Technician licensure examination",
        category: "Laboratory Specialist/Technician",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Radiologic Technologist Licensure Examination",
        slug: "srtle",
        abbreviation: "SRTLE",
        description: "SRTLE - Radiologic Technologist/Technician licensure examination",
        category: "Radiologic Technologist/Technician",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Saudi Respiratory Care Licensure Examination",
        slug: "srcle",
        abbreviation: "SRCLE",
        description: "SRCLE - Respiratory Care Practitioner licensure examination",
        category: "Respiratory Care Practitioner",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      // Specialty Board Examinations
      {
        name: "Internal Medicine Board",
        slug: "internal-medicine-board",
        abbreviation: "IM Board",
        description: "Internal Medicine specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Family Medicine Board",
        slug: "family-medicine-board",
        abbreviation: "FM Board",
        description: "Family Medicine specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Pediatrics Board",
        slug: "pediatrics-board",
        abbreviation: "Peds Board",
        description: "Pediatrics specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Surgery Board",
        slug: "surgery-board",
        abbreviation: "Surgery Board",
        description: "Surgery specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Obstetrics & Gynecology Board",
        slug: "obgyn-board",
        abbreviation: "OB/GYN Board",
        description: "Obstetrics & Gynecology specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Emergency Medicine Board",
        slug: "emergency-medicine-board",
        abbreviation: "EM Board",
        description: "Emergency Medicine specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Psychiatry Board",
        slug: "psychiatry-board",
        abbreviation: "Psych Board",
        description: "Psychiatry specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Critical Care Medicine",
        slug: "critical-care-board",
        abbreviation: "CCM Board",
        description: "Critical Care Medicine specialty board examination",
        category: "Doctor (Specialist)",
        isActive: true,
        isPublic: true,
        isPremium: false,
        requiredTier: "free",
        createdBy: systemUserId,
        isCompleted: false,
        isPinned: false,
        totalSubjects: 0,
        totalQuestions: 0,
        totalFiles: 0,
        createdAt: now,
        updatedAt: now,
      },
    ];

    // Check for existing exams to avoid duplicates
    const existingExams = await ctx.db.query("exams").collect();
    const existingNames = new Set(existingExams.map((e) => e.name.toLowerCase()));
    const existingSlugs = new Set(existingExams.map((e) => e.slug?.toLowerCase()).filter(Boolean));

    let added = 0;
    let skipped = 0;

    for (const exam of exams) {
      // Skip if exam with same name or slug already exists
      if (existingNames.has(exam.name.toLowerCase()) || existingSlugs.has(exam.slug.toLowerCase())) {
        skipped++;
        continue;
      }

      await ctx.db.insert("exams", exam);
      added++;
    }

    return {
      success: true,
      added,
      skipped,
      total: exams.length,
      message: `Successfully added ${added} exams. ${skipped} were skipped (already exist).`,
    };
  },
});
